window.SITE_CONTENT = {
  profile: {
    name: "吴雪凡",
    tagline: "文字 / 摄影 / 影像",
    intro:
      "这里会长期收录我的文字、摄影作品和剪辑视频。更新不追赶噪音，只保留真正想留下的片段。",
    about:
      "我把这里当作一个长期生长的个人档案：文字记录想法，照片保存现场，视频整理时间里的运动。",
    facts: [
      ["媒介", "文字、摄影、视频剪辑"],
      ["关注", "城市、日常、记忆、影像叙事"],
      ["状态", "持续整理与更新中"],
    ],
  },
  writing: [
    {
      id: "first-writing",
      title: "第一篇文字的标题",
      date: "2026-05-21",
      category: "随笔",
      excerpt: "这里放一段摘要，说明这篇文字关于什么。之后可以替换成完整文章链接。",
      url: "#",
    },
    {
      id: "after-shooting-note",
      title: "一次拍摄之后的记录",
      date: "2026-05-12",
      category: "札记",
      excerpt: "可以写下拍摄现场、剪辑想法，或者某个阶段的观察。",
      url: "#",
    },
    {
      id: "personal-archive-note",
      title: "长期维护一个私人档案",
      date: "2026-04-28",
      category: "备忘",
      excerpt: "这个网站适合慢慢积累，不需要一次性变得完整。",
      url: "#",
    },
  ],
  photos: [
    {
      id: "250131-singapore-airport",
      title: "樟宜机场-Changi Airport",
      date: "2025-01-31",
      category: "新加坡",
      location: "新加坡-樟宜机场",
      description: "花园景观，令人震惊的园林水平",
      src: "assets/photos/250131-singapore-airport.JPG",
    },
    {
      id: "250204-singapore-church",
      title: "圣安德烈教堂-St Andrew's Cathedral",
      date: "2025-02-04",
      category: "新加坡",
      location: "新加坡-圣安德烈教堂",
      description: "在这里体会一种宗教宁静。",
      src: "assets/photos/250204-singapore-church.JPG",
    },
    {
      id: "250204-singapore-muslim",
      title: "苏丹回教堂-Sultan Mosque",
      date: "2025-01-31",
      category: "新加坡",
      location: "新加坡-苏丹回教堂",
      description: "在这里体会一种宗教宁静。",
      src: "assets/photos/250204-singapore-muslim.JPG",
    },
    {
      id: "250202-singapore-beach",
      title: "圣淘沙-Sentosa",
      date: "2025-02-02",
      category: "新加坡",
      location: "新加坡-圣淘沙岛",
      description: "海浪、沙滩、野餐，身为游客想象当地居民的生活",
      src: "assets/photos/250202-singapore-beach.JPG",
    },
    {
      id: "250201-singapore-wolf",
      title: "那串晶莹的口水",
      date: "2025-02-01",
      category: "新加坡",
      location: "新加坡-夜间动物园 Night Safari",
      description: "有点遗憾没从有蝙蝠飞过头顶的游步道行走。",
      src: "assets/photos/250201-singapore-wolf.JPG",
    },
    {
      id: "250201-singapore-lizard",
      title: "两爬魅力",
      date: "2025-02-01",
      category: "新加坡",
      location: "新加坡-河川生态园-Mandai River Wonders",
      description: "好想摸摸它的皮肤是什么触感。",
      src: "assets/photos/250201-singapore-lizard.JPG",
    },
    {
      id: "250301-light-01",
      title: "虚拟手电筒-Fictitious flashlight",
      date: "2025-03-01",
      category: "灵感",
      location: "杭州-吴山明美术馆",
      description: "虚拟手电，实体照亮",
      src: "assets/photos/250301-light-01.JPG",
    },
    {
      id: "260307-yulan-01",
      title: "玉兰",
      date: "2026-03-07",
      category: "日常",
      location: "杭州",
      description: "如玉质感。",
      src: "assets/photos/260307-yulan-01.JPG",
    },
    {
      id: "260516-street-light",
      title: "街角的光",
      date: "2026-05-16",
      category: "城市",
      location: "Shanghai",
      description: "可以在这里写下拍摄时间、地点、器材或当时的观察。",
      src: "",
    },
    {
      id: "260502-rain-window",
      title: "雨后的窗",
      date: "2026-05-02",
      category: "日常",
      location: "Home",
      description: "照片说明会出现在大图弹窗里，适合放一句简短的现场记录。",
      src: "",
    },
    {
      id: "260419-evening-crowd",
      title: "傍晚的人群",
      date: "2026-04-19",
      category: "纪实",
      location: "Street",
      description: "如果暂时没有图片文件，页面会先显示占位视觉。",
      src: "",
    },
  ],
  photoCollections: [
    {
      id: "singapore-2025",
      title: "Singapore 2025",
      subtitle: "新加坡",
      dateRange: "2025.01-2025.02",
      location: "Singapore",
      description: "围绕城市、园林、宗教建筑与游客视角的旅行观察。",
      cover: "250131-singapore-airport",
      featured: true,
      photoIds: [
        "250131-singapore-airport",
        "250204-singapore-church",
        "250204-singapore-muslim",
        "250202-singapore-beach",
        "250201-singapore-wolf",
        "250201-singapore-lizard",
      ],
    },
    {
      id: "religious-quiet",
      title: "Religious Quiet",
      subtitle: "宗教宁静",
      dateRange: "2025.01-2025.02",
      location: "Singapore",
      description: "关于宗教建筑、白色墙面、空间秩序与安静感的照片。",
      cover: "250204-singapore-church",
      featured: true,
      photoIds: ["250204-singapore-church", "250204-singapore-muslim"],
    },
    {
      id: "light-inspiration",
      title: "Light / Inspiration",
      subtitle: "光与灵感",
      dateRange: "2025.03",
      location: "Hangzhou",
      description: "从展览现场、光线装置和偶然的观看经验里收集灵感。",
      cover: "250301-light-01",
      featured: true,
      photoIds: ["250301-light-01"],
    },
    {
      id: "daily-observation",
      title: "Daily Observation",
      subtitle: "日常观察",
      dateRange: "Ongoing",
      location: "Hangzhou / Shanghai",
      description: "把日常里短暂出现的颜色、植物、窗与街角保存下来。",
      cover: "260307-yulan-01",
      featured: true,
      photoIds: ["260307-yulan-01"],
    },
  ],
  videos: [
    {
      title: "一分钟影像练习",
      date: "2026-05-20",
      description: "把剪辑视频文件放进 assets/videos，再把链接填到这里。",
      url: "#",
      thumb: "",
    },
    {
      title: "旅行片段",
      date: "2026-05-05",
      description: "也可以使用 Bilibili、YouTube、Vimeo 等外部视频链接。",
      url: "#",
      thumb: "",
    },
  ],
};
