window.SITE_CONTENT = {
  profile: {
    name: "吴雪凡",
    tagline: "文字 / 摄影 / 影像",
    intro:
      "这里会长期收录我的文字、摄影作品和剪辑视频。更新不追赶噪音，只保留真正想留下的片段。",
    about:
      "我把这里当作一个长期生长的个人档案：文字记录想法，照片保存现场，视频整理时间里的运动。",
    facts: [
      ["媒介", "文字、摄影、视频剪辑"],
      ["关注", "城市、日常、记忆、影像叙事"],
      ["状态", "持续整理与更新中"],
    ],
  },
  writing: [
    {
      id: "first-writing",
      title: "第一篇文字的标题",
      date: "2026-05-21",
      category: "随笔",
      excerpt: "这里放一段摘要，说明这篇文字关于什么。之后可以替换成完整文章链接。",
      url: "#",
    },
    {
      id: "after-shooting-note",
      title: "一次拍摄之后的记录",
      date: "2026-05-12",
      category: "札记",
      excerpt: "可以写下拍摄现场、剪辑想法，或者某个阶段的观察。",
      url: "#",
    },
    {
      id: "personal-archive-note",
      title: "长期维护一个私人档案",
      date: "2026-04-28",
      category: "备忘",
      excerpt: "这个网站适合慢慢积累，不需要一次性变得完整。",
      url: "#",
    },
  ],
  photos: [
    {
      id: "250131-singapore-airport",
      title: "樟宜机场-Changi Airport",
      titleEn: "Changi Airport",
      date: "2025-01-31",
      category: "新加坡",
      location: "新加坡-樟宜机场",
      locationEn: "Singapore - Changi Airport",
      description: "花园景观，令人震惊的园林水平",
      descriptionEn: "Garden-like scenery, with a striking level of landscape design.",
      src: "assets/photos/display/250131-singapore-airport.webp",
      keywords: [],
      keywordsEn: [],
      relatedWritingIds: [],
      exhibitionIds: [],
    },
    {
      id: "250131-singapore-police-office",
      title: "旧禧街警察局",
      titleEn: "Old Hill Street Police Station",
      date: "2025-01-31",
      category: "新加坡",
      location: "新加坡-旧禧街警察局",
      locationEn: "Singapore - Old Hill Street Police Station",
      description: "警察局的彩虹夜景。",
      descriptionEn: "A rainbow-lit night view of the former police station.",
      src: "assets/photos/display/250131-singapore-police-office.webp",
      keywords: ["新加坡", "街景"],
      keywordsEn: ["Singapore","Street Scene"],
      relatedWritingIds: [],
      exhibitionIds: ["singapore-2025"],
    },
    {
      id: "250204-singapore-church",
      title: "圣安德烈教堂-St Andrew's Cathedral",
      titleEn: "St Andrew's Cathedral",
      date: "2025-02-04",
      category: "新加坡",
      location: "新加坡-圣安德烈教堂",
      locationEn: "Singapore - St Andrew's Cathedral",
      description: "在这里体会一种宗教宁静。",
      descriptionEn: "A moment of religious quietness felt in this place.",
      src: "assets/photos/display/250204-singapore-church.webp",
      keywords: [],
      keywordsEn: [],
      relatedWritingIds: [],
      exhibitionIds: [],
    },
    {
      id: "250204-singapore-muslim",
      title: "苏丹回教堂-Sultan Mosque",
      titleEn: "Sultan Mosque",
      date: "2025-01-31",
      category: "新加坡",
      location: "新加坡-苏丹回教堂",
      locationEn: "Singapore - Sultan Mosque",
      description: "在这里体会一种宗教宁静。",
      descriptionEn: "A moment of religious quietness felt in this place.",
      src: "assets/photos/display/250204-singapore-muslim.webp",
      keywords: [],
      keywordsEn: [],
      relatedWritingIds: [],
      exhibitionIds: [],
    },
    {
      id: "250202-singapore-beach",
      title: "圣淘沙-Sentosa",
      titleEn: "Sentosa",
      date: "2025-02-02",
      category: "新加坡",
      location: "新加坡-圣淘沙岛",
      locationEn: "Singapore - Sentosa Island",
      description: "海浪、沙滩、野餐，身为游客想象当地居民的生活",
      descriptionEn: "Waves, beach, picnic, and a traveler imagining the lives of local residents.",
      src: "assets/photos/display/250202-singapore-beach.webp",
      keywords: [],
      keywordsEn: [],
      relatedWritingIds: [],
      exhibitionIds: [],
    },
    {
      id: "250201-singapore-wolf",
      title: "那串晶莹的口水",
      titleEn: "That Glistening Thread of Saliva",
      date: "2025-02-01",
      category: "新加坡",
      location: "新加坡-夜间动物园 Night Safari",
      locationEn: "Singapore - Night Safari",
      description: "有点遗憾没从有蝙蝠飞过头顶的游步道行走。",
      descriptionEn: "A small regret: I did not walk through the trail where bats fly overhead.",
      src: "assets/photos/display/250201-singapore-wolf.webp",
      keywords: [],
      keywordsEn: [],
      relatedWritingIds: [],
      exhibitionIds: [],
    },
    {
      id: "250201-singapore-lizard",
      title: "两爬魅力",
      titleEn: "The Charm of Reptiles",
      date: "2025-02-01",
      category: "新加坡",
      location: "新加坡-河川生态园-Mandai River Wonders",
      locationEn: "Singapore - Mandai River Wonders",
      description: "好想摸摸它的皮肤是什么触感。",
      descriptionEn: "I keep wondering what its skin would feel like to touch.",
      src: "assets/photos/display/250201-singapore-lizard.webp",
      keywords: [],
      keywordsEn: [],
      relatedWritingIds: [],
      exhibitionIds: [],
    },
    {
      id: "250203-singapore-leaves",
      title: "几种绿色",
      titleEn: "Several Greens",
      date: "2025-02-03",
      category: "新加坡",
      location: "新加坡-云雾林 Cloud forest",
      locationEn: "Singapore - Cloud Forest",
      description: "清爽绿色。",
      descriptionEn: "A refreshing shade of green.",
      src: "assets/photos/display/250203-singapore-leaves.webp",
      keywords: ["新加坡", "植物", "绿色"],
      keywordsEn: ["Singapore", "Plants", "Green"],
      relatedWritingIds: [],
      exhibitionIds: ["singapore-2025", "plants-and-animals"],
    },
    {
      id: "250204-singapore-alley",
      title: "高楼林立之下",
      titleEn: "Beneath the High-Rises",
      date: "2025-02-04",
      category: "新加坡",
      location: "新加坡-某路",
      locationEn: "Singapore - An Unnamed Road",
      description: "正面人潮汹涌、色彩缤纷；背面人迹罕至、灰雾蒙蒙。这里似乎才是背后的高楼生长之源。",
      descriptionEn: "At the front, crowds and vivid color; at the back, few people and a grey haze. This seems to be where the high-rises behind it take root.",
      src: "assets/photos/display/250204-singapore-alley.webp",
      keywords: ["新加坡", "街景", "灵光"],
      keywordsEn: ["Singapore", "Street Scene", "Glimpse"],
      relatedWritingIds: [],
      exhibitionIds: ["singapore-2025"],
    },
    {
      id: "250204-singapore-river",
      title: "游船",
      titleEn: "River Cruise",
      date: "2025-02-04",
      category: "新加坡",
      location: "新加坡-某河",
      locationEn: "Singapore - An Unnamed River",
      description: "和他们一起打量这个城市。",
      descriptionEn: "Looking over the city together with them.",
      src: "assets/photos/display/250204-singapore-river.webp",
      keywords: ["新加坡", "街景"],
      keywordsEn: ["Singapore", "Street Scene"],
      relatedWritingIds: [],
      exhibitionIds: ["singapore-2025"],
    },
    {
      id: "250301-light-01",
      title: "虚拟手电筒-Fictitious flashlight",
      titleEn: "Fictitious Flashlight",
      date: "2025-03-01",
      category: "灵感",
      location: "杭州-吴山明美术馆",
      locationEn: "Hangzhou - Wushan Ming Art Museum",
      description: "虚拟手电，实体照亮",
      descriptionEn: "A virtual flashlight, physically illuminating.",
      src: "assets/photos/display/250301-light-01.webp",
      keywords: [],
      keywordsEn: [],
      relatedWritingIds: [],
      exhibitionIds: [],
    },
    {
      id: "250301-hangzhou-bay",
      title: "远近滨江",
      titleEn: "Riverside, Near and Far",
      date: "2025-03-01",
      category: "杭州",
      location: "杭州-六和塔",
      locationEn: "Hangzhou - Liuhe Pagoda",
      description: "登高而远望。",
      descriptionEn: "Climbing high and looking into the distance.",
      src: "assets/photos/display/250301-hangzhou-bay.webp",
      keywords: ["杭州", "街景"],
      keywordsEn: ["Hangzhou", "Street Scene"],
      relatedWritingIds: [],
      exhibitionIds: ["hangzhou-2025"],
    },
    {
      id: "250301-hangzhou-insect",
      title: "黄钩蛱蝶 Polygonia c-aureum",
      titleEn: "Polygonia c-aureum",
      date: "2025-03-01",
      category: "杭州",
      location: "杭州",
      locationEn: "Hangzhou",
      description: "后翅腹面有一对白色的“钩子”斑点，成虫过冬，早春易见。",
      descriptionEn: "A pair of white hook-shaped marks appears on the underside of the hindwings. Adults overwinter and are often seen in early spring.",
      src: "assets/photos/display/250301-hangzhou-insect.webp",
      keywords: ["杭州", "昆虫"],
      keywordsEn: ["Hangzhou", "Insect"],
      relatedWritingIds: [],
      exhibitionIds: ["hangzhou-2025", "plants-and-animals"],
    },
    {
      id: "250301-hangzhou-shancha18",
      title: "山茶 十八学士",
      titleEn: "Camellia: Shiba Xueshi",
      date: "2025-03-01",
      category: "杭州",
      location: "杭州",
      locationEn: "Hangzhou",
      description: "最美的山茶。",
      descriptionEn: "The most beautiful camellia.",
      src: "assets/photos/display/250301-hangzhou-shancha18.webp",
      keywords: ["杭州", "植物"],
      keywordsEn: ["Hangzhou", "Plants"],
      relatedWritingIds: [],
      exhibitionIds: ["hangzhou-2025", "plants-and-animals"],
    },
    {
      id: "250404-plant-can",
      title: "枫杨喝红牛会长的更快吗",
      titleEn: "Would a Chinese Wingnut Grow Faster with Red Bull?",
      date: "2025-04-04",
      category: "合肥",
      location: "合肥",
      locationEn: "Hefei",
      description: "枫杨喝红牛会长的更快吗？",
      descriptionEn: "Would a Chinese wingnut grow faster if it drank Red Bull?",
      src: "assets/photos/display/250404-plant-can.webp",
      keywords: ["合肥", "植物", "灵光"],
      keywordsEn: ["Hefei", "Plants", "Glimpse"],
      relatedWritingIds: [],
      exhibitionIds: ["hefei", "plants-and-animals"],
    },
    {
      id: "250810-taiping-tree",
      title: "远山树林",
      titleEn: "Distant Mountains and Woods",
      date: "2025-08-10",
      category: "日常",
      location: "太平",
      locationEn: "Taiping",
      description: "远山到山，山到树林，是谁想把小树推下",
      descriptionEn: "From distant mountains to mountains, from mountains to woods: who is trying to push the little tree down?",
      src: "assets/photos/display/250810-taiping-tree.webp",
      keywords: ["太平", "灵光", "风光"],
      keywordsEn: ["Taiping", "Glimpse", "Landscape"],
      relatedWritingIds: [],
      exhibitionIds: ["taiping", "landscape"],
    },
    {
      id: "250819-hongkong-buildings1",
      title: "招牌",
      titleEn: "Signboard",
      date: "2025-08-19",
      category: "香港",
      location: "香港 维多利亚港",
      locationEn: "Hong Kong - Victoria Harbour",
      description: "2025的定格。",
      descriptionEn: "A still frame of 2025.",
      src: "assets/photos/display/250819-hongkong-buildings1.webp",
      keywords: ["香港", "街景"],
      keywordsEn: ["Hong Kong", "Street Scene"],
      relatedWritingIds: [],
      exhibitionIds: ["hong-kong-2025"],
    },
    {
      id: "250819-hongkong-buildings2",
      title: "摩天轮",
      titleEn: "Ferris Wheel",
      date: "2025-08-19",
      category: "香港",
      location: "香港 维多利亚港",
      locationEn: "Hong Kong - Victoria Harbour",
      description: "JOIN THE JOURNEY",
      descriptionEn: "JOIN THE JOURNEY",
      src: "assets/photos/display/250819-hongkong-buildings2.webp",
      keywords: ["香港", "街景"],
      keywordsEn: ["Hong Kong", "Street Scene"],
      relatedWritingIds: [],
      exhibitionIds: ["hong-kong-2025"],
    },
    {
      id: "250819-hongkong-buildings3",
      title: "黑云压城",
      titleEn: "Dark Clouds Over the City",
      date: "2025-08-19",
      category: "香港",
      location: "香港 维多利亚港",
      locationEn: "Hong Kong - Victoria Harbour",
      description: "城欲摧",
      descriptionEn: "The city seems about to fall.",
      src: "assets/photos/display/250819-hongkong-buildings3.webp",
      keywords: ["香港", "街景"],
      keywordsEn: ["Hong Kong", "Street Scene"],
      relatedWritingIds: [],
      exhibitionIds: ["hong-kong-2025"],
    },
    {
      id: "250819-hongkong-buildings4",
      title: "纵深",
      titleEn: "Depth",
      date: "2025-08-19",
      category: "香港",
      location: "香港 大馆",
      locationEn: "Hong Kong - Tai Kwun",
      description: "空间如剪",
      descriptionEn: "Space, as if cut.",
      src: "assets/photos/display/250819-hongkong-buildings4.webp",
      keywords: ["香港", "街景"],
      keywordsEn: ["Hong Kong", "Street Scene"],
      relatedWritingIds: [],
      exhibitionIds: ["hong-kong-2025"],
    },
    {
      id: "250819-hongkong-buildings5",
      title: "第四面墙",
      titleEn: "The Fourth Wall",
      date: "2025-08-19",
      category: "香港",
      location: "香港 大馆",
      locationEn: "Hong Kong - Tai Kwun",
      description: "你面前还有一面玻璃墙",
      descriptionEn: "There is another glass wall in front of you.",
      src: "assets/photos/display/250819-hongkong-buildings5.webp",
      keywords: ["香港", "街景"],
      keywordsEn: ["Hong Kong", "Street Scene"],
      relatedWritingIds: [],
      exhibitionIds: ["hong-kong-2025"],
    },
    {
      id: "250820-hongkong-lkh1",
      title: "林家谦",
      titleEn: "Terence Lam",
      date: "2025-08-20",
      category: "香港",
      location: "香港 红磡",
      locationEn: "Hong Kong - Hung Hom",
      description: "香港之行缘起。",
      descriptionEn: "The reason this Hong Kong trip began.",
      src: "assets/photos/display/250820-hongkong-lkh1.webp",
      keywords: ["香港", "人像", "音乐现场"],
      keywordsEn: ["Hong Kong", "Portrait", "Live Music"],
      relatedWritingIds: [],
      exhibitionIds: ["hong-kong-2025"],
    },
    {
      id: "250820-hongkong-lkh2",
      title: "White Summer",
      titleEn: "White Summer",
      date: "2025-08-20",
      category: "香港",
      location: "香港 红磡",
      locationEn: "Hong Kong - Hung Hom",
      description: "记得。",
      descriptionEn: "Remember.",
      src: "assets/photos/display/250820-hongkong-lkh2.webp",
      keywords: ["香港", "音乐现场"],
      keywordsEn: ["Hong Kong", "Live Music"],
      relatedWritingIds: [],
      exhibitionIds: ["hong-kong-2025"],
    },
    {
      id: "250820-hongkong-traffic-light",
      title: "红磡街市",
      titleEn: "Hung Hom Market",
      date: "2025-08-20",
      category: "香港",
      location: "香港 红磡",
      locationEn: "Hong Kong - Hung Hom",
      description: "旅游时去菜市，体会当地人的生活。",
      descriptionEn: "Visiting a market while traveling, to feel the life of local residents.",
      src: "assets/photos/display/250820-hongkong-traffic-light.webp",
      keywords: ["香港", "街景"],
      keywordsEn: ["Hong Kong", "Street Scene"],
      relatedWritingIds: [],
      exhibitionIds: ["hong-kong-2025"],
    },
    {
      id: "250820-hongkong-tree",
      title: "美丽的树",
      titleEn: "A Beautiful Tree",
      date: "2025-08-20",
      category: "香港",
      location: "香港 圣士提反女子中学 St. Stephen’s Girl’s College",
      locationEn: "Hong Kong - St. Stephen's Girls' College",
      description: "循着萧红踪迹而来，为树倾倒。",
      descriptionEn: "I came following the traces of Xiao Hong, and fell for the tree.",
      src: "assets/photos/display/250820-hongkong-tree.webp",
      keywords: ["香港", "街景", "植物"],
      keywordsEn: ["Hong Kong", "Street Scene", "Plants"],
      relatedWritingIds: [],
      exhibitionIds: ["hong-kong-2025", "plants-and-animals"],
    },
    {
      id: "250821-hongkong-zoo-bird",
      title: "蓝鹤",
      titleEn: "Blue Crane",
      date: "2025-08-20",
      category: "香港",
      location: "香港动植物公园 Hong Kong Zoological and Botanical Gardens",
      locationEn: "Hong Kong Zoological and Botanical Gardens",
      description: "一直忧郁而优雅的走来走去，可能是刻板行为。",
      descriptionEn: "It kept walking back and forth, melancholic and elegant; perhaps a stereotyped behavior.",
      src: "assets/photos/display/250821-hongkong-zoo-bird.webp",
      keywords: ["香港", "鸟"],
      keywordsEn: ["Hong Kong", "Birds"],
      relatedWritingIds: [],
      exhibitionIds: ["hong-kong-2025", "plants-and-animals"],
    },
    {
      id: "250822-hongkong-stanley1",
      title: "赤柱一瞥",
      titleEn: "A Glimpse of Stanley",
      date: "2025-08-22",
      category: "香港",
      location: "香港 赤柱 Hong Kong Stanley",
      locationEn: "Hong Kong - Stanley",
      description: "怎知道霎眼就到赤柱了。",
      descriptionEn: "Who knew Stanley would arrive in the blink of an eye.",
      src: "assets/photos/display/250822-hongkong-stanley1.webp",
      keywords: ["香港", "街景"],
      keywordsEn: ["Hong Kong", "Street Scene"],
      relatedWritingIds: [],
      exhibitionIds: ["hong-kong-2025"],
    },
    {
      id: "250822-hongkong-stanley2",
      title: "赤柱码头",
      titleEn: "Stanley Pier",
      date: "2025-08-22",
      category: "香港",
      location: "香港 赤柱 Hong Kong Stanley",
      locationEn: "Hong Kong - Stanley",
      description: "从此这里永远有一部分我。",
      descriptionEn: "From now on, a part of me will always remain here.",
      src: "assets/photos/display/250822-hongkong-stanley2.webp",
      keywords: ["香港", "风光"],
      keywordsEn: ["Hong Kong", "Landscape"],
      relatedWritingIds: [],
      exhibitionIds: ["hong-kong-2025", "landscape"],
    },
    {
      id: "250822-hongkong-stanley3",
      title: "赤柱码头远景",
      titleEn: "Stanley Pier from Afar",
      date: "2025-08-22",
      category: "香港",
      location: "香港 赤柱 Hong Kong Stanley",
      locationEn: "Hong Kong - Stanley",
      description: "从此这里永远有一部分我。",
      descriptionEn: "From now on, a part of me will always remain here.",
      src: "assets/photos/display/250822-hongkong-stanley3.webp",
      keywords: ["香港", "风光"],
      keywordsEn: ["Hong Kong", "Landscape"],
      relatedWritingIds: [],
      exhibitionIds: ["hong-kong-2025", "landscape"],
    },
    {
      id: "250822-hongkong-stanley4",
      title: "鲜切与扎根",
      titleEn: "Fresh-Cut and Rooted",
      date: "2025-08-22",
      category: "香港",
      location: "香港 赤柱 Hong Kong Stanley",
      locationEn: "Hong Kong - Stanley",
      description: "都是生存。",
      descriptionEn: "Both are ways of surviving.",
      src: "assets/photos/display/250822-hongkong-stanley4.webp",
      keywords: ["香港", "植物", "街景"],
      keywordsEn: ["Hong Kong", "Plants", "Street Scene"],
      relatedWritingIds: [],
      exhibitionIds: ["hong-kong-2025", "plants-and-animals"],
    },
    {
      id: "250822-hongkong-stanley5",
      title: "赤柱监狱",
      titleEn: "Stanley Prison",
      date: "2025-08-22",
      category: "香港",
      location: "香港 赤柱 Hong Kong Stanley",
      locationEn: "Hong Kong - Stanley",
      description: "无间道",
      descriptionEn: "Infernal Affairs",
      src: "assets/photos/display/250822-hongkong-stanley5.webp",
      keywords: ["香港", "街景"],
      keywordsEn: ["Hong Kong", "Street Scene"],
      relatedWritingIds: [],
      exhibitionIds: ["hong-kong-2025"],
    },
    {
      id: "250822-hongkong-university-bird",
      title: "红耳鹎",
      titleEn: "Red-whiskered Bulbul",
      date: "2025-08-22",
      category: "香港",
      location: "香港大学Hong Kong University",
      locationEn: "The University of Hong Kong",
      description: "在香港大学尽展鸟人本色。",
      descriptionEn: "At the University of Hong Kong, I fully became a bird person.",
      src: "assets/photos/display/250822-hongkong-university-bird.webp",
      keywords: ["香港", "鸟"],
      keywordsEn: ["Hong Kong", "Birds"],
      relatedWritingIds: [],
      exhibitionIds: ["hong-kong-2025", "plants-and-animals"],
    },
    {
      id: "251123-hangzhou-huagangguanyu",
      title: "花港观鱼",
      titleEn: "Viewing Fish at Flower Harbor",
      date: "2025-11-23",
      category: "杭州",
      location: "杭州 西湖 花港观鱼 Hangzhou West Lake",
      locationEn: "Hangzhou West Lake - Viewing Fish at Flower Harbor",
      description: "也不一定要观鱼，抬头看看也很好。",
      descriptionEn: "You do not always have to watch the fish; looking up is good too.",
      src: "assets/photos/display/251123-hangzhou-huagangguanyu.webp",
      keywords: ["杭州", "街景", "植物"],
      keywordsEn: ["Hangzhou", "Street Scene", "Plants"],
      relatedWritingIds: [],
      exhibitionIds: ["hangzhou-2025", "plants-and-animals"],
    },
    {
      id: "251123-hangzhou-taiziwan",
      title: "曲与直",
      titleEn: "Curves and Straights",
      date: "2025-11-23",
      category: "杭州",
      location: "杭州 西湖 太子湾公园 Hangzhou West Lake",
      locationEn: "Hangzhou West Lake - Taiziwan Park",
      description: "树间好像伫立着谁的轮廓。",
      descriptionEn: "A figure seems to stand among the trees.",
      src: "assets/photos/display/251123-hangzhou-taiziwan.webp",
      keywords: ["杭州", "灵光", "植物"],
      keywordsEn: ["Hangzhou", "Glimpse", "Plants"],
      relatedWritingIds: [],
      exhibitionIds: ["hangzhou-2025", "plants-and-animals", "glimpse"],
    },
    {
      id: "251116-hangzhou-jaguar",
      title: "豹",
      titleEn: "Leopard",
      date: "2025-11-16",
      category: "杭州",
      location: "杭州动物园",
      locationEn: "Hangzhou Zoo",
      description: "对视或放空。",
      descriptionEn: "A gaze, or a moment of blankness.",
      src: "assets/photos/display/251116-hangzhou-jaguar.webp",
      keywords: ["杭州", "动物"],
      keywordsEn: ["Hangzhou", "Animals"],
      relatedWritingIds: [],
      exhibitionIds: ["hangzhou-2025", "plants-and-animals"],
    },
    {
      id: "251228-hangzhou-tower",
      title: "深秋雷锋塔",
      titleEn: "Leifeng Pagoda in Late Autumn",
      date: "2025-12-28",
      category: "杭州",
      location: "杭州雷锋塔",
      locationEn: "Hangzhou - Leifeng Pagoda",
      description: "深秋色彩是自然的魔法。",
      descriptionEn: "The colors of late autumn are nature's magic.",
      src: "assets/photos/display/251228-hangzhou-tower.webp",
      keywords: ["杭州", "风光"],
      keywordsEn: ["Hangzhou", "Landscape"],
      relatedWritingIds: [],
      exhibitionIds: ["hangzhou-2025", "landscape"],
    },
    {
      id: "260307-yulan-01",
      title: "玉兰",
      titleEn: "Yulan Magnolia",
      date: "2026-03-07",
      category: "日常",
      location: "杭州",
      locationEn: "Hangzhou",
      description: "如玉质感。",
      descriptionEn: "A jade-like texture.",
      src: "assets/photos/display/260307-yulan-01.webp",
      keywords: [],
      keywordsEn: [],
      relatedWritingIds: [],
      exhibitionIds: [],
    },
  ],
  photoCollections: [
    {
      id: "singapore-2025",
      title: "Singapore 2025",
      subtitle: "新加坡",
      dateRange: "2025.01-2025.02",
      location: "Singapore",
      description: "围绕城市、园林、宗教建筑与游客视角的旅行观察。",
      featured: true,
      photoIds: [
        "250131-singapore-airport",
        "250204-singapore-church",
        "250204-singapore-muslim",
        "250202-singapore-beach",
        "250201-singapore-wolf",
        "250201-singapore-lizard",
        "250131-singapore-police-office",
        "250203-singapore-leaves",
        "250204-singapore-alley",
        "250204-singapore-river",
      ],
    },
    {
      id: "hong-kong-2025",
      title: "Hong Kong 2025",
      subtitle: "香港",
      dateRange: "2025.08",
      location: "Hong Kong",
      description: "围绕密集建筑、街道信号、校园与海边空间的香港观察。",
      featured: true,
      photoIds: [
        "250819-hongkong-buildings1",
        "250819-hongkong-buildings2",
        "250819-hongkong-buildings3",
        "250819-hongkong-buildings4",
        "250819-hongkong-buildings5",
        "250820-hongkong-lkh1",
        "250820-hongkong-lkh2",
        "250820-hongkong-traffic-light",
        "250820-hongkong-tree",
        "250821-hongkong-zoo-bird",
        "250822-hongkong-stanley1",
        "250822-hongkong-stanley2",
        "250822-hongkong-stanley3",
        "250822-hongkong-stanley4",
        "250822-hongkong-stanley5",
        "250822-hongkong-university-bird",
      ],
    },
    {
      id: "hangzhou-2025",
      title: "Hangzhou 2025",
      subtitle: "杭州",
      dateRange: "2025",
      location: "Hangzhou",
      description: "关于杭州的植物、建筑、展览现场与公园空间。",
      featured: true,
      photoIds: [
        "250301-light-01",
        "250301-hangzhou-bay",
        "250301-hangzhou-insect",
        "250301-hangzhou-shancha18",
        "250404-plant-can",
        "251123-hangzhou-huagangguanyu",
        "251123-hangzhou-taiziwan",
        "251116-hangzhou-jaguar",
        "251228-hangzhou-tower",
        "260307-yulan-01",
      ],
    },
    {
      id: "religious-quiet",
      title: "Religious Quiet",
      subtitle: "宗教宁静",
      dateRange: "2025.01-2025.02",
      location: "Singapore",
      description: "关于宗教建筑、白色墙面、空间秩序与安静感的照片。",
      featured: true,
      photoIds: ["250204-singapore-church", "250204-singapore-muslim"],
    },
    {
      id: "light-inspiration",
      title: "Light / Inspiration",
      subtitle: "光与灵感",
      dateRange: "2025.03",
      location: "Hangzhou",
      description: "从展览现场、光线装置和偶然的观看经验里收集灵感。",
      featured: true,
      photoIds: ["250301-light-01", "250301-hangzhou-bay"],
    },
    {
      id: "plants-and-animals",
      title: "Plants & Animals",
      subtitle: "植物与动物",
      dateRange: "Ongoing",
      location: "Hangzhou / Hong Kong / Singapore",
      description: "把植物、动物与自然形态作为持续出现的观看线索。",
      featured: true,
      photoIds: [
        "250201-singapore-wolf",
        "250201-singapore-lizard",
        "250203-singapore-leaves",
        "250301-hangzhou-insect",
        "250301-hangzhou-shancha18",
        "250404-plant-can",
        "250810-taiping-tree",
        "250820-hongkong-tree",
        "250821-hongkong-zoo-bird",
        "250822-hongkong-university-bird",
        "251123-hangzhou-huagangguanyu",
        "251123-hangzhou-taiziwan",
        "251116-hangzhou-jaguar",
        "260307-yulan-01",
      ],
    },
  ],
  videos: [
    {
      title: "一分钟影像练习",
      date: "2026-05-20",
      description: "把剪辑视频文件放进 assets/videos，再把链接填到这里。",
      url: "#",
      thumb: "",
    },
    {
      title: "旅行片段",
      date: "2026-05-05",
      description: "也可以使用 Bilibili、YouTube、Vimeo 等外部视频链接。",
      url: "#",
      thumb: "",
    },
  ],
};
