window.SITE_CONTENT = {
  profile: {
    name: "吴雪凡",
    tagline: "文字 / 摄影 / 影像",
    intro:
      "这里会长期收录我的文字、摄影作品和剪辑视频。更新不追赶噪音，只保留真正想留下的片段。",
    about:
      "这是一个个人作品与日常观察的长期档案。文字记录想法，照片保存现场，视频整理时间里的运动。",
    facts: [
      ["所在地", "上海 / 可移动"],
      ["关注", "城市、日常、记忆、影像叙事"],
      ["联系", "把邮箱或社交主页放在这里"],
    ],
  },
  writing: [
    {
      title: "第一篇文字的标题",
      date: "2026-05-21",
      category: "随笔",
      excerpt: "这里放一段摘要，说明这篇文字关于什么。之后可以替换成完整文章链接。",
      url: "#",
    },
    {
      title: "一次拍摄之后的记录",
      date: "2026-05-12",
      category: "札记",
      excerpt: "可以写下拍摄现场、剪辑想法，或者某个阶段的观察。",
      url: "#",
    },
    {
      title: "长期维护一个私人档案",
      date: "2026-04-28",
      category: "备忘",
      excerpt: "这个网站适合慢慢积累，不需要一次性变得完整。",
      url: "#",
    },
  ],
  photos: [
    {
      title: "樟宜机场-Changi Airport",
      date: "2025-01-31",
      category: "新加坡",
      location: "新加坡-樟宜机场",
      description: "花园景观，令人震惊的园林水平",
      src: "assets/photos/250131-singapore-airport.JPG",
    },
    {
      title: "圣安德烈教堂-St Andrew's Cathedral",
      date: "2025-02-04",
      category: "新加坡",
      location: "新加坡-圣安德烈教堂",
      description: "在这里体会一种宗教宁静。",
      src: "assets/photos/250204-singapore-church.JPG",
    },
    {
      title: "苏丹回教堂-Sultan Mosque",
      date: "2025-01-31",
      category: "新加坡",
      location: "新加坡-苏丹回教堂",
      description: "在这里体会一种宗教宁静。",
      src: "assets/photos/250204-singapore-muslim.JPG",
    },
    {
      title: "圣淘沙-Sentosa",
      date: "2025-02-02",
      category: "新加坡",
      location: "新加坡-圣淘沙岛",
      description: "海浪、沙滩、野餐，身为游客想象当地居民的生活",
      src: "assets/photos/250202-singapore-beach.JPG",
    },
    {
      title: "那串晶莹的口水",
      date: "2025-02-01",
      category: "新加坡",
      location: "新加坡-夜间动物园 Night Safari",
      description: "有点遗憾没从有蝙蝠飞过头顶的游步道行走。",
      src: "assets/photos/250201-singapore-wolf.JPG",
    },
    {
      title: "两爬魅力",
      date: "2025-02-01",
      category: "新加坡",
      location: "新加坡-河川生态园-Mandai River Wonders",
      description: "好想摸摸它的皮肤是什么触感。",
      src: "assets/photos/250201-singapore-lizard.JPG",
    },
    {
      title: "虚拟手电筒-Fictitious flashlight",
      date: "2025-03-01",
      category: "灵感",
      location: "杭州-吴山明美术馆",
      description: "虚拟手电，实体照亮",
      src: "assets/photos/250301-light-01.JPG",
    },
    {
      title: "玉兰",
      date: "2026-03-07",
      category: "日常",
      location: "杭州",
      description: "如玉质感。",
      src: "assets/photos/260307-yulan-01.JPG",
    },
    {
      title: "街角的光",
      date: "2026-05-16",
      category: "城市",
      location: "Shanghai",
      description: "可以在这里写下拍摄时间、地点、器材或当时的观察。",
      src: "",
    },
    {
      title: "雨后的窗",
      date: "2026-05-02",
      category: "日常",
      location: "Home",
      description: "照片说明会出现在大图弹窗里，适合放一句简短的现场记录。",
      src: "",
    },
    {
      title: "傍晚的人群",
      date: "2026-04-19",
      category: "纪实",
      location: "Street",
      description: "如果暂时没有图片文件，页面会先显示占位视觉。",
      src: "",
    },
  ],
  videos: [
    {
      title: "一分钟影像练习",
      date: "2026-05-20",
      description: "把剪辑视频文件放进 assets/videos，再把链接填到这里。",
      url: "#",
      thumb: "",
    },
    {
      title: "旅行片段",
      date: "2026-05-05",
      description: "也可以使用 Bilibili、YouTube、Vimeo 等外部视频链接。",
      url: "#",
      thumb: "",
    },
  ],
};
